pipeline {
agent any



parameters {
string(name:"VERSION", defaultValue:'1', description:'version to deploy')
choice(name:"Version", choices : ['1.1', '1.2', '1.3'], description:'')
booleanParam(name:'executeTests', defaultValue:true, description:"skip tests")
}



tools {
maven 'maven'
}




environment {
ORG_NAME = "team2"
APP_NAME = "trainer-service"
APP_VERSION = "1.0-SNAPSHOT"
APP_CONTEXT_ROOT = "/"
APP_LISTENING_PORT = "8200"
TEST_CONTAINER_NAME = "ci-${APP_NAME}-${BUILD_NUMBER}"
PREV_CONTAINER_NAME="ci-${APP_NAME}-${currentBuild.previousBuild.number}"
}



stages {
stage('Compile') {
steps {
echo "-=- compiling project -=-"
bat "mvn clean compile"
}
}



stage('Package') {



when {
expression {
params.executeTests
}
}



steps {
echo "-=- packaging project -=-"
bat "mvn package -DskipTests=true"
archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
}
}


stage('Pulling sonarqube') {
steps {
echo "====Pulling sonarqube===='"
bat "docker pull sonarqube:latest"
}
}

stage('Pulling mongo') {
steps {
echo "====Pulling mongo===='"
bat "docker pull mongo:latest"
}
}



stage('Building trainer-service Docker image') {
steps {
echo "-=- build Docker image -=-"
bat "docker build -t trainer-service:1.0 ."
}
}







}
}